# 1. Identificación del Microservicio y Puerto
spring.application.name=microservicio-notificaciones
server.port=8082

# 2. Configuración de Conexión a PostgreSQL
# Reemplaza 'bd_notificaciones' por el nombre de la base de datos que creaste para este servicio
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_notificaciones
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' creará automáticamente la tabla 'notificacion' y los enums si no existen
spring.jpa.hibernate.ddl-auto=update
# Muestra en la consola las consultas SQL que Spring ejecuta (ideal para desarrollo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true